# Generated by Django 2.1.5 on 2021-02-01 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='date_time',
            new_name='update_time',
        ),
    ]
